# 系统配置
application:
  processes: 1  # runtime.GOMAXPROCS(processes)

upstream:
  - id: server1
    balance: random
    server: [127.0.0.1:8080,127.0.0.1:8081,127.0.0.1:8082]
  - id: server2
    balance: random
    server: [127.0.0.1:8083,127.0.0.1:8084]

# http 服务配置
http:
  server:
    - listen: 80
      server_name: 127.0.0.1
      location:
        - pattern: "/*"
          proxy_pass: server1
          request: {"head1": "m1"}
          response: {"Server": "webrouting"}
    - listen: 80
      server_name: localhost
      location:
        - pattern: "/*"
          proxy_pass: server1
          request: {"head1": "m1"}
          response: {"Server": "webrouting"}